services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    networks:
      - elasticnet
    env_file:
      - .env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elasticnet

networks:
  elasticnet:
    driver: bridge
